apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: k8s-mcp
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: k8s-mcp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-mcp-server
    app.kubernetes.io/version: latest
    helm.sh/chart: k8s-mcp-server-0.1.0
  name: k8s-mcp-k8s-mcp-server
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8s-mcp
      app.kubernetes.io/name: k8s-mcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: k8s-mcp
        app.kubernetes.io/name: k8s-mcp-server
    spec:
      containers:
      - env:
        - name: SERVER_MODE
          value: sse
        - name: SERVER_PORT
          value: "8080"
        - name: KUBECONFIG
          value: /home/appuser/.kube/config
        image: ginnux/k8s-mcp-server:latest
        imagePullPolicy: IfNotPresent
        name: k8s-mcp-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/appuser/.kube
          name: kubeconfig
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-mcp-k8s-mcp-server
      serviceAccountName: k8s-mcp-k8s-mcp-server
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: k8s-mcp-kubeconfig
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-19T22:51:15Z"
    lastUpdateTime: "2025-07-19T22:51:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-19T22:47:45Z"
    lastUpdateTime: "2025-07-19T22:51:15Z"
    message: ReplicaSet "k8s-mcp-k8s-mcp-server-67445bdc67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
