apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: k8s-mcp
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: k8s-mcp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-mcp-server
    app.kubernetes.io/version: latest
    helm.sh/chart: k8s-mcp-server-0.1.0
  name: k8s-mcp-k8s-mcp-server
  namespace: {{ .Release.Namespace }}
spec:
  - 10.97.101.50
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: k8s-mcp
    app.kubernetes.io/name: k8s-mcp-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
