apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: rustdocs-mcp
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: rustdocs-mcp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rust-docs-mcp-server
    app.kubernetes.io/version: 2.0.0
    helm.sh/chart: rust-docs-mcp-server-0.1.0
  name: rustdocs-mcp-rust-docs-mcp-server
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: 10.109.85.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: health
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: rustdocs-mcp
    app.kubernetes.io/name: rust-docs-mcp-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
